config/routes.rb
Rainout::Application.routes.draw do

  resources :numbers

  resources :facilities

  resources :charges

  devise_for :users, :controllers => { :registrations => "registrations" }
  root :to => 'static_pages#home'
  get 'company', to: 'static_pages#company'
  get 'blog', to: 'static_pages#blog'
  get 'contact_us', to: 'static_pages#contact_us'
  get 'find', to: 'numbers#find'
  post 'numbers/new', to: 'numbers#new'
  post 'charges/new', to: 'charges#new'
  

end

app/models/facility.rb
class Facility < ActiveRecord::Base
	belongs_to :user
	belongs_to :number

	validates :name, presence: true
	validates :status, presence: true
	validates :hotline, presence: true
end

app/models/number.rb
class Number < ActiveRecord::Base
	attr_accessor :stripe_card_token
	belongs_to :user
	has_many :facilities

	validates :number, presence: true

	def save_with_payment
		if valid?
			customer = Stripe::Customer.create(card: stripe_card_token)
			self.stripe_customer_token = customer.id
			save!
		end
	rescue Stripe::InvalidRequestError => e
		logger.error "Stripe error while creating customer: #{e.message}"
		errors.add :base, "There was a problem with your credit card."
		false
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :email, presence: true
   validates :password, presence: true
   validates :password_confirmation, presence: true

   has_many :facilities
   has_many :numbers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :phone_number
  end

  def stored_location_for(resource)
  	nil 
  end

  def after_sign_in_path_for(resource)
  	facilities_path
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => current_user.email,
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )
      
      redirect_to new_facility_path, notice: 'Thank you for the payment. Now setup your facility.'
	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facility = Facility.new 
    @facilities = current_user.facilities.order('created_at DESC')
    @numbers =current_user.numbers.map { |number| [ number.number, number.number ] }
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @facility = current_user.facilities.find(params[:id]) rescue redirect_to(facilities_path)
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
    @numbers = current_user.numbers.map { |number| [ number.number, number.number ] }
  end

  # GET /facilities/1/edit
  def edit
    @facility = current_user.facilities.find(params[:id]) rescue redirect_to(facilities_path)
    @numbers = current_user.numbers.map { |number| [ number.number, number.number ] }
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = current_user.facilities.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to facilities_path, notice: 'Facility was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facility }
      else
        format.html { render action: 'new' }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to facilities_path, notice: 'Facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :hotline, :status, :message)
    end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = current_user.numbers.order('created_at DESC')
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
    @numbers = current_user.numbers.find(params[:id]) rescue redirect_to(numbers_path)
  end

  def find
    @number = Number.new
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
    redirect_to numbers_path
  end

  # POST /numbers
  # POST /numbers.json
  def create
    @number = current_user.numbers.new(number_params)

    respond_to do |format|
      if @number.save_with_payment
        format.html { redirect_to new_facility_path, notice: 'Thank you for your purchase. Now set up your first facility using your new hotline.' }
        format.json { render action: 'show', status: :created, location: @number }
      else
        format.html { render action: 'new' }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1
  # PATCH/PUT /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to @number, notice: 'Number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1
  # DELETE /numbers/1.json
  def destroy
    @number.destroy
    respond_to do |format|
      format.html { redirect_to numbers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:number)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

	def after_sign_up_path_for(resource)
		find_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def home
  end

  def company
  end

  def blog
  end

  def contact_us
  end

  def search_numbers
  end

  def saved_number
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/facilities/_form.html.erb
<%= simple_form_for(@facility) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :hotline, collection: @numbers, :prompt => "Select Hotline" %>
    <%= f.input :status, prompt: "Select Status", collection: ["Open", "Close", "Custom"] %>
    <%= f.input :message, :input_html => { :rows => 8 } %>
    <p>* required input</p>
  </div>

  <div class="form-actions" style="text-align: center; padding-right: 40px;">
    <%= f.button :submit, :class => "center btn btn-success btn-edit", :style => "margin: auto;" %>
  </div>
<% end %>

app/views/facilities/_sidebar.html.erb
<div class="col-md-2">
  <div class="well">
    <ul class="nav bs-navbar">
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-list"></span>Facilities'.html_safe, facilities_path, { :class => "active" } %>
      </li>
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-bell"></span>Notifications'.html_safe, '#' %>
      </li>
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-tasks"></span>Account'.html_safe, edit_user_registration_path %>
      </li>
    </ul>
  </div>
</div>

app/views/facilities/edit.html.erb
<div id="modal-edit-fields">
	<div class="modal-dialog">
		<div class="modal-content">
	  		<div class="modal-header">
	    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    		<h2 class="modal-title" id="myModalLabel">Update Facility</h2>
	  		</div>
	  		<div class="modal-body">
	    		<div class="small-container">
	      			<%= render 'form' %>
	  	  		</div>
	 	 	</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

app/views/facilities/index.html.erb
<div class="row">
  <%= render 'sidebar' %>
  <div class="col-md-10">
    <h1 class="center">My Facilities</h1>
  <div class="well">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Hotline</th>
          <th>Status</th>
          <th>Message</th>
          <th style="width: 50px;"></th>
          <th style="width: 70px;"></th>
        </tr>
      </thead>

      <tbody>
        <% @facilities.each do |facility| %>
          <tr>
            <td><%= facility.name %></td>
            <td><a href="tel:+1<%= facility.hotline %>"><%= facility.hotline %></td>
            <td><%= facility.status %></td>
            <td><%= facility.message %></td>
            <td><a data-toggle="modal" data-target="#myModal2" data-remote="<%= edit_facility_path(facility) %> #modal-edit-fields" class="btn btn-primary btn-edit">edit</a></td>
            <td><%= link_to '<button class="btn btn-danger btn-edit">Destroy</button>'.html_safe, facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <br>
    <div class="center" style="margin-bottom: 50px;">
      <%= link_to '<button class="center btn btn-primary btn-fac" data-toggle="modal" data-target="#myModal1">Add New Facility</button>'.html_safe, new_facility_path %>
    </div>

    <!-- Create Modal -->
    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h2 class="modal-title" id="myModalLabel">Add New Facility</h2>
          </div>
          <div class="modal-body">
            <div class="small-container">
              <%= render 'form' %>
            </div>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

     <!-- Edit Modal -->
    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div><!-- /.modal --> 
  </div>
</div>

app/views/facilities/new.html.erb
<div id="modal-edit-fields">
	<div class="modal-dialog">
		<div class="modal-content">
	  		<div class="modal-header">
	    		<h2 class="modal-title" id="myModalLabel">Add New Facility</h2>
	  		</div>
	  		<div class="modal-body">
	    		<div class="small-container">
	      			<%= render 'form' %>
	  	  		</div>
	 	 	</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facility.name %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @facility.abbr %>
</p>

<p>
  <strong>Status:</strong>
  <%= @facility.status %>
</p>

<p>
  <strong>Message:</strong>
  <%= @facility.message %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/_footer.html.erb
<footer class="center">
	<ul style="padding-top: 39px;">
		<li><%= link_to "Home", root_path %></li>
		<li class="divider"></li>
		<li><%= link_to "Company", company_path %></li>
		<li class="divider"></li> 
		<li><%= link_to "Blog", 'http://blog.rainouthotline.com' %></li>
		<li class="divider"></li>
		<li><%= link_to "Contact Us", contact_us_path %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container" id="nav-container">
    	<div class="navbar-header">
    		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    			<span class="icon-bar"></span>
           	 	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
        	</button>
        	<a class="navbar-brand" href="/"><img style="margin-right: 10px;" src="/assets/Apt-Prps_Sanit.gif" class="img-rounded">Rainouthotline.com</a>
        </div>

        <div class="navbar-collapse collapse">
        	<ul class="nav navbar-nav navbar-right">
                <% if current_user %>
        		  <li><%= link_to "Facilities", facilities_path %></li>
                <% else %>
                    <li><%= link_to "Home", root_path %></li>
                <% end %>
        		<li><%= link_to "Company", company_path %></li> 
        		<li><%= link_to "Blog", 'http://blog.rainouthotline.com' %></li>
        		<li><%= link_to "Contact Us", contact_us_path %></li>
                <% if current_user %>
                    <li class="divider-vertical"></li>
                    <li style="padding: 11px 0px 11px 15px; color: black; line-height: 26px;"><%= current_user.email %></li>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <% end %>
        	</ul>
        </div>
    </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_phone.html.erb
<script type="text/javascript">
	jQuery(function($){
	$("#phone").mask("(999) 999-9999");
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rainout</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <script src="/assets/jquery.maskedinput.js"></script>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div id="wrap">
			<%= render 'layouts/header' %>
			<div class="container">
			 	<%= render 'layouts/messages' %>
				<%= yield %>
			</div>
		</div>
		<%= render 'layouts/footer' %>
		<script src="assets/modal.js"></script>
		<script>
		  	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  	ga('create', 'UA-48109222-1', 'rainouthotline.com');
		  	ga('send', 'pageview');
		</script>
	</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/numbers/_form.html.erb
<%= simple_form_for(@number) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/numbers/_sidebar.html.erb
<div class="col-md-2">
  <div class="well">
    <ul class="nav bs-navbar">
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-list"></span>Facilities'.html_safe, facilities_path %>
      </li>
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-bell"></span>Notifications'.html_safe, '#' %>
      </li>
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-tasks"></span>Account'.html_safe, edit_user_registration_path %>
      </li>
      <li class="sidenav-link">
        <%= link_to '<span class="glyphicon glyphicon-phone"></span>Hotline Numbers'.html_safe, numbers_path, { :class => "active" } %>
    </ul>
  </div>
</div>

app/views/numbers/choose.html.erb
<% 
  account_sid = 'ACfb6ad995a6df4e72ed305a5084a5c399'
  auth_token = '0d4d4203a00a79dbcf81d355bacdc3df'
   
  client = Twilio::REST::Client.new(account_sid, auth_token)
 
  search_params = {}
  %w[area_code].each do |p|
    search_params[p] = params[p] unless params[p].nil? || params[p].empty?
  end
%>

<%= simple_form_for(@number, :url => new_charge_path) %>
<%= f.error_notification %>
<% local_numbers = client.account.available_phone_numbers.get('US').local %>
<% numbers = local_numbers.list(search_params) %>
<h3>Choose a hotline</h3>
<div class="form-inputs">
  <%= f.input :number, collection: 'number.friendly_name', as: :radio %>
</div>
<div class="form-actions">
  <%= f.button :submit %>
</div>

app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<%= render 'form' %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

app/views/numbers/find.html.erb
<% 
  account_sid = 'ACfb6ad995a6df4e72ed305a5084a5c399'
  auth_token = '0d4d4203a00a79dbcf81d355bacdc3df'
   
  client = Twilio::REST::Client.new(account_sid, auth_token)
 
  search_params = {}
  %w[area_code].each do |p|
    search_params[p] = params[p] unless params[p].nil? || params[p].empty?
  end
%>

<div id="modal-edit-fields">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="myModalLabel">Find a hotline number</h2>
        </div>
        <div class="modal-body">
          <div class="small-container">
            <form method="POST" action="numbers/new">
              <label>Choose by area code (e.g. 512): </label><input type="text" size="7" name="area_code"/><br/><br/>
              <div class="center" style="margin-top: 30px; margin-right: 50px;">
                <input type="submit" class="btn btn-primary" value="SEARCH"/>
              </div>
            </form>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/numbers/index.html.erb
<div class="row">
  <%= render 'sidebar' %>
  <div class="col-md-10">
    <h1 style="padding-left: 30px;">Hotline Numbers</h1>
    <div class="well">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Number</th>
            <th style="width: 75px;"></th>
          </tr>
        </thead>

        <tbody>
          <% @numbers.each do |number| %>
            <tr>
              <td><%= number.number %></td>
              <td><%= link_to '<button class="btn btn-danger btn-edit">Remove</button>'.html_safe, number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
    <div class="center" style="margin-bottom: 50px;">
      <%= link_to '<button class="center btn btn-primary btn-fac">Add Hotline Number</button>'.html_safe, find_path %>
    </div>
  </div>
</div>

app/views/numbers/new.html.erb
<% 
  account_sid = 'ACfb6ad995a6df4e72ed305a5084a5c399'
  auth_token = '0d4d4203a00a79dbcf81d355bacdc3df'
   
  client = Twilio::REST::Client.new(account_sid, auth_token)
 
  search_params = {}
  %w[area_code].each do |p|
    search_params[p] = params[p] unless params[p].nil? || params[p].empty?
  end
%>
<div id="modal-edit-fields">
	<div class="modal-dialog">
    	<div class="modal-content">
        	<div class="modal-header">
          	<h2 class="modal-title center" id="myModalLabel">Copy a hotline you'd like to use and paste it into the field</h2>
        	</div>
        	<div class="modal-body">
          		<div class="small-container" id="number">
					<% begin %>
						<% local_numbers = client.account.available_phone_numbers.get('US').local %>
						<% numbers = local_numbers.list(search_params) %>

						<% unless numbers.empty? %>
							<%= simple_form_for(@number) do |f| %>
								<%= f.error_notification %>
								<% numbers.each do |number| %>
									<label style="padding: 5px"><%= number.friendly_name %></label>
								<% end %>
								<div class="form-inputs" style="margin-top: 5px;">
								  <%= f.input :number, input_html: { id: 'phone' } %>
								</div>
								<%= render 'layouts/phone' %>
								<div class="form-actions" style="text-align: center; padding-right: 40px;">
									<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          								data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
         								data-description="A month's subscription"
          								data-amount="500"></script>
								</div>
							<% end %>
						<% else %>
							<h3 class="center"><b>Sorry!</b> Twilio doesn't have any numbers available that match those constraints.</h3>
					    <% end %>
					<% rescue StandardError => e %>
						<h3 class="center"><b>Sorry! </b><%= e.message %></h3>
					<% end %>
				</div>
      		</div>
   		 </div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
</div>

app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @number.number %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>

app/views/static_pages/blog.html.erb
<h1>StaticPages#blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>

app/views/static_pages/company.html.erb
<h1>StaticPages#company</h1>
<p>Find me in app/views/static_pages/company.html.erb</p>

app/views/static_pages/contact_us.html.erb
<h1>WE ARE... RAINOUT HOTLINE!</h1>
<p>that should answer all your questions</p>

app/views/static_pages/home.html.erb
<h1 class="center"><b>Reliable & Easy Rainout Lines</b></h1>
<div style="max-width: 260px; margin: 0 auto 45px;">
	<% if current_user %>
		<%= link_to '<button type="button" class="btn btn-primary btn-lg btn-block">My Facilities</button>'.html_safe, facilities_path %>
	<% else %>
		<%= link_to '<button type="button" class="btn btn-primary btn-lg btn-block">Get My Rainout Line</button>'.html_safe, new_user_registration_path %>
		<div class="center">
			<h2>Or</h2>
			<h2><%= link_to "Sign in", new_user_session_path %></h2>
		</div>
	<% end %>
</div>

app/views/static_pages/numbers.html.erb
<% 
  account_sid = 'ACfb6ad995a6df4e72ed305a5084a5c399'
  auth_token = '0d4d4203a00a79dbcf81d355bacdc3df'
   
  client = Twilio::REST::Client.new(account_sid, auth_token)
 
  search_params = {}
  %w[area_code].each do |p|
    search_params[p] = params[p] unless params[p].nil? || params[p].empty?
  end
%>


  <% begin %>
    <% local_numbers = client.account.available_phone_numbers.get('US').local %>
    <% numbers = local_numbers.list(search_params) %>
   
    <% unless numbers.empty? %>
      <h3>Choose a number</h3>
      <% numbers.each do |number| %>
        <form  action='/charges/new'>
        <label><%= number.friendly_name %></label>
        <input type='hidden' name='PhoneNumber' value='<%= number.friendly_name %>' />
        <input type='submit' value='BUY' /></form>
      <% end %>
    <% else %>
      <h3 class="center"><b>Sorry!</b> Twilio doesn't have any numbers available that match those constraints.</h3>
    <% end %>
  <% rescue StandardError => e %>
    <h3 class="center"><b>Sorry! </b><%= e.message %></h3>
  <% end %>

app/views/static_pages/saved_number.html.erb
<h1>test</h1>
<p> you got <%= PhoneNumber %></p>

app/views/static_pages/search_numbers.html.erb
<div id="modal-edit-fields">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="myModalLabel">Find a hotline number</h2>
        </div>
        <div class="modal-body">
          <div class="small-container">
            <form method="POST">
              <label>Choose by area code (e.g. 512): </label><input type="text" size="7" name="area_code"/><br/><br/>
              <div class="center" style="margin-top: 30px; margin-right: 50px;">
                <input type="submit" class="btn btn-primary" value="SEARCH"/>
              </div>
            </form>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>